export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="pt-BR">
      <head>
        <meta charSet="UTF-8"/>
        <title>Desafio Cefis</title>
      </head>
      <body>{children}</body>
    </html>
  )
}
